[package]
name = "nebulous-fleet-duplicator"
version = "0.1.0"
edition = "2021"

[dependencies]
nebulous-data = { path = "../nebulous-data", features = ["rand"] }
rand = { version = "0.8.5", default-features = false, features = ["std", "getrandom"] }
rand_xoshiro = { version = "0.6.0" }
