name = "Energy Transfer"
tags = []
cost_budget_total = 787
cost_budget_spare = 76
missile_selections = []
socket_data = "omlodWxsX3R5cGVya2V5c3RvbmVfZGVzdHJveWVyZ3NvY2tldHOVoW1jb21wb25lbnRfa2V5a21rNjRfY2Fubm9uom1jb21wb25lbnRfa2V5b3ZfbF9zMl9sYXVuY2hlcmd2YXJpYW50oXFNYWdhemluZUNvbXBvbmVudKFxbWFnYXppbmVfY29udGVudHOgoW1jb21wb25lbnRfa2V5c21rMjBfZGVmZW5kZXJfcF9kX3ShbWNvbXBvbmVudF9rZXlzbWsyMF9kZWZlbmRlcl9wX2RfdKJtY29tcG9uZW50X2tleXF2X2xfczEyM19sYXVuY2hlcmd2YXJpYW50oXFNYWdhemluZUNvbXBvbmVudKFxbWFnYXppbmVfY29udGVudHOjdlN0b2NrL0VBMTIgQ2hhZmYgRGVjb3kIdlN0b2NrL0VBMjAgRmxhcmUgRGVjb3kCd1N0b2NrL0VBOTkgQWN0aXZlIERlY295AaFtY29tcG9uZW50X2tleXNtazIwX2RlZmVuZGVyX3BfZF90oW1jb21wb25lbnRfa2V5cW1rNjAwX2JlYW1fY2Fubm9uoW1jb21wb25lbnRfa2V5aGJlcnRoaW5nom1jb21wb25lbnRfa2V5c3JlaW5mb3JjZWRfbWFnYXppbmVndmFyaWFudKFxTWFnYXppbmVDb21wb25lbnShcW1hZ2F6aW5lX2NvbnRlbnRzpG9TdG9jay8yMG1tIFNsdWcZJxB0U3RvY2svMjUwbW0gSEUgU2hlbGwYMngYU3RvY2svMjUwbW0gSEUtUlBGIFNoZWxsGDJ0U3RvY2svMjUwbW0gQVAgU2hlbGwYMqFtY29tcG9uZW50X2tleXByZWluZm9yY2VkX2NfaV9joW1jb21wb25lbnRfa2V5dHBsYW50X2NvbnRyb2xfY2VudGVyoW1jb21wb25lbnRfa2V5cHNtYWxsX2RfY19sb2NrZXKhbWNvbXBvbmVudF9rZXl1cmVpbmZvcmNlZF9kX2NfbG9ja2VyoW1jb21wb25lbnRfa2V5cHJhcGlkX2RfY19sb2NrZXKhbWNvbXBvbmVudF9rZXlvZl9yNDgwMF9yZWFjdG9yoW1jb21wb25lbnRfa2V5dWZfbTIzMF93aGlwbGFzaF9kcml2ZaFtY29tcG9uZW50X2tleXVmX3IzMzAwX21pY3JvX3JlYWN0b3KhbWNvbXBvbmVudF9rZXl4HGZvY3VzZWRfcGFydGljbGVfYWNjZWxlcmF0b3KhbWNvbXBvbmVudF9rZXl0cl9tNTBfcGFyYWxsYXhfcmFkYXKhbWNvbXBvbmVudF9rZXl3YWRhcHRpdmVfcmFkYXJfcmVjZWl2ZXKhbWNvbXBvbmVudF9rZXl4HGZvY3VzZWRfcGFydGljbGVfYWNjZWxlcmF0b3I="

[equipment_summary]
has_intelligence = false
has_illuminator = false
has_deception_module = false
has_missile_identification = false
fire_control = ["radar"]
jamming = []
sensors = ["radar"]

[[equipment_summary.weapons]]
ballistic = "middle"

[[equipment_summary.weapons]]
point_defense = "defender"

[[equipment_summary.weapons]]
standard_missile = "size1"

[[equipment_summary.weapons]]
energy_beam = "near"

[equipment_summary.missile_cells]
standard_missile_size2 = 24
standard_missile_size1 = 23
