point_limit_target = 3000

# stage 0: hull selection
[[stages]]
steps = 20
max_trunks = 32
max_branches = 32
passthrough_trunks = 8

[fleet_planning]
hull_limit = 10
hull_budget_jitter = 0.25
excessive_general_hull_score = 0.0
excessive_utility_hull_score = -70.0
general_hull_variance_score = -5.0
utility_hull_variance_score = 2.5
unbudgeted_points_threshold = 175
unbudgeted_points_score = -0.0125

[fleet_planning.purposes.brawler]
meta = "general"
budget = 0.6
score = 100.0
short_range_combat = 2.00
medium_range_combat = 1.50
long_range_combat = 0.00
missile_combat = 0.25
survivability = 1.75

[fleet_planning.purposes.sniper]
meta = "general"
budget = 0.6
score = 95.0
short_range_combat = 0.00
medium_range_combat = 0.25
long_range_combat = 2.00
missile_combat = 0.75
survivability = 0.25

[fleet_planning.purposes.missileer]
meta = "general"
budget = 1.0
score = 100.0
short_range_combat = 0.25
medium_range_combat = 0.50
long_range_combat = 0.00
missile_combat = 2.00
survivability = 0.25

[fleet_planning.purposes.scout]
meta = "utility"
budget = 0.4
score = 105.0
short_range_combat = 0.00
medium_range_combat = 0.00
long_range_combat = 0.00
missile_combat = 0.00
point_defense = 1.25
survivability = 0.50
sensor_coverage = 2.0

[fleet_planning.purposes.escort]
meta = "utility"
budget = 0.4
score = 100.0
short_range_combat = 0.25
medium_range_combat = 0.25
long_range_combat = 0.25
missile_combat = 0.25
point_defense = 2.00
survivability = 1.50
sensor_coverage = 1.50

[hull_planning]
redundancy_score = -2.5

[hulls.sprinter_corvette]
score = 1.0
points_budget_min = 200
points_budget_max = 450
purposes = ["brawler", "missileer", "scout", "escort"]

[hulls.raines_frigate]
score = 1.0
points_budget_min = 300
points_budget_max = 700
purposes = ["brawler", "missileer", "scout", "escort"]

[hulls.keystone_destroyer]
score = 1.0
points_budget_min = 400
points_budget_max = 1000
purposes = ["brawler", "sniper", "missileer", "escort"]

[hulls.vauxhall_light_cruiser]
score = 1.0
points_budget_min = 800
points_budget_max = 1400
purposes = ["brawler", "missileer"]

[hulls.axford_heavy_cruiser]
score = 1.0
points_budget_min = 1100
points_budget_max = 1800
purposes = ["brawler", "sniper", "missileer"]

[hulls.solomon_battleship]
score = 1.0
points_budget_min = 2200
points_budget_max = 3000
purposes = ["brawler", "sniper", "missileer"]

[hulls.shuttle_clipper]
score = 0.875
points_budget_min = 200
points_budget_max = 400
purposes = ["missileer", "scout"]

[hulls.tugboat_clipper]
score = 1.0
points_budget_min = 300
points_budget_max = 500
purposes = ["brawler", "missileer", "scout", "escort"]

[hulls.cargo_feeder_monitor]
score = 1.0
points_budget_min = 500
points_budget_max = 800
purposes = ["brawler", "sniper", "missileer", "scout", "escort"]

[hulls.ocello_command_cruiser]
score = 0.875
points_budget_min = 1300
points_budget_max = 1700
purposes = ["brawler", "sniper"]

[hulls.bulk_freighter_line_ship]
score = 1.0
points_budget_min = 800
points_budget_max = 1500
purposes = ["brawler", "sniper", "missileer"]

[hulls.container_liner_line_ship]
score = 1.125
points_budget_min = 2400
points_budget_max = 3000
purposes = ["missileer"]
