[package]
name = "nebulous-data"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.14.3", features = ["derive", "min_const_generics"] }
itertools = { version = "0.12.1" }
thiserror = { version = "1.0" }
xml = { path = "../xml" }
