[package]
name = "nebulous-fleet-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0" }
chumsky = { version = "0.9.3" }
clap = { version = "4.5.18", features = ["derive"] }
indexmap = { version = "2.5.0" }
nebulous-data = { path = "../nebulous-data", features = ["rand", "serde"] }
rand = { version = "0.8.5" }
serde = { version = "1.0", features = ["derive"] }
thiserror = { version = "1.0" }

[dependencies.singlefile]
git = "https://github.com/ScottyThePilot/singlefile"
rev = "f4f5a60a18fe20a3369ce204c9dff535bdf051c7"

[dependencies.singlefile-formats]
git = "https://github.com/ScottyThePilot/singlefile"
rev = "f4f5a60a18fe20a3369ce204c9dff535bdf051c7"
features = ["toml-serde", "cbor-serde", "base64"]
